version: '3.8'
services:
  redis-7000:
    image: redis:6.2
    container_name: redis-7000
    ports:
      - "7000:6379"
    volumes:
      - ./cluster/7000:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-7001:
    image: redis:6.2
    container_name: redis-7001
    ports:
      - "7001:6379"
    volumes:
      - ./cluster/7001:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-7002:
    image: redis:6.2
    container_name: redis-7002
    ports:
      - "7002:6379"
    volumes:
      - ./cluster/7002:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-7003:
    image: redis:6.2
    container_name: redis-7003
    ports:
      - "7003:6379"
    volumes:
      - ./cluster/7003:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-7004:
    image: redis:6.2
    container_name: redis-7004
    ports:
      - "7004:6379"
    volumes:
      - ./cluster/7004:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-7005:
    image: redis:6.2
    container_name: redis-7005
    ports:
      - "7005:6379"
    volumes:
      - ./cluster/7005:/data
      - ./redis.conf:/redis/redis.conf
    command: ["redis-server", "/redis/redis.conf"]
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge