version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 1073741824
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    networks:
      - es-net
    ports:
      - 9200:9200
networks:
  es-net:
    driver: bridge
volumes:
  esdata:
    driver: local