version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - signoz

  query-service:
    image: signoz/query-service:latest
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_URL=clickhouse:9000
    networks:
      - signoz

  otel-collector:
    image: signoz/signoz-otel-collector:0.111.36
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - clickhouse
    networks:
      - signoz

  frontend:
    image: signoz/frontend:latest
    ports:
      - "3301:3301"
    environment:
      - REACT_APP_API_ENDPOINT=http://query-service:8080
    depends_on:
      - query-service
    networks:
      - signoz

networks:
  signoz:
    driver: bridge

volumes:
  clickhouse-data:
