version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - ELASTIC_PASSWORD=anhnt93@  # đặt mật khẩu cho user mặc định "elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /f/log/logfile.log:/usr/share/logstash/logs/logfile.log
    ports:
      - "5044:5044"   # Beats input
      - "5000:5000/tcp" # TCP input
      - "9600:9600"   # Monitoring API
      - "8888:8080"
    depends_on:
      - elasticsearch
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # - /f/logs_tt/nginx/logfile.log:/logs/nginx/logfile.log:ro
      - /f/logs_tt/app1/logfile.log:/logs/app1/logfile.log:ro
      - /f/logs_tt/app2/logfile.log:/logs/app2/logfile.log:ro
    depends_on:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
