version: '3'
services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-1"]
    ports:
      - "7001:6379"
    volumes:
      - redis-node-1-data:/data
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-2"]
    ports:
      - "7002:6379"
    volumes:
      - redis-node-2-data:/data
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-3"]
    ports:
      - "7003:6379"
    volumes:
      - redis-node-3-data:/data
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-4"]
    ports:
      - "7004:6379"
    volumes:
      - redis-node-4-data:/data
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf","--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-5"]
    ports:
      - "7005:6379"
    volumes:
      - redis-node-5-data:/data
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf","--cluster-node-timeout", "5000", "--appendonly", "yes","--no-appendfsync-on-rewrite","no","--cluster-announce-port","6379","--cluster-announce-bus-port","16379","--cluster-announce-ip","redis-node-6"]
    ports:
      - "7006:16379"
    volumes:
      - redis-node-6-data:/data
    networks:
      - redis-cluster

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  redis-cluster:
    driver: bridge